config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  resources :cocktails do
    resources :doses, only: [:create, :destroy]
    resources :reviews, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false }
  has_many :ingredients, through: :doses
  has_one_attached :photo

  def avg_score
    sum = 0
    reviews.each { |review| sum += review.rating }
    reviews.count.positive? ? sum / reviews.count : sum
  end
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  validates :ingredient_id, presence: true
  belongs_to :cocktail
  validates :cocktail_id, presence: true
  validates :description, presence: true
  validates :cocktail_id, uniqueness: { scope: :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many  :doses
  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :cocktail_id, presence: true
  validates :rating, presence: true
  validates :rating, inclusion: { within: (1..5), message: "Value must be 1 to 5"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  require 'open-uri'

  before_action :set_cocktail, only: [:edit, :show, :destroy, :update]

  def index
    @cocktails = Cocktail.all
  end

  def show
    @dose = Dose.new
    @review = Review.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(params_cocktail)
    default_image if @cocktail.photo.attachment.nil?
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :show
    end
  end

  def edit; end

  def update
    @cocktail.update(params_cocktail)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :edit
    end
  end

  def destroy
    @cocktail.delete
    redirect_to cocktails_path
  end

  private

  def params_cocktail
    params.require(:cocktail).permit(:name, :instructions, :photo_url, :photo)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
    # @doses = Dose.where(cocktail_id: @cocktail.id)
    @doses = @cocktail.doses
    @reviews = @cocktail.reviews
    # @reviews = Review.where(cocktail_id: @cocktail.id)
    @score = @cocktail.avg_score
  end

  def default_image
    file = URI.open('https://res.cloudinary.com/dr4pzn94d/image/upload/v1612376373/kamila-maciejewska-UBX5-_ajTXw-unsplash_eo62cn.jpg')
    @cocktail.photo.attach(io: file, filename: 'default.jpg', content_type: 'image/jpg')
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  before_action :set_cocktail, only: [:create, :edit, :update]

  def create
    @dose = Dose.new(params_dose)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      @score = @cocktail.avg_score
      @reviews = @cocktail.reviews
      @doses = @cocktail.doses
      @review = Review.new
      # redirect_to cocktail_path(@cocktail)
      render "cocktails/show"
    end
  end

  def edit; end

  def update; end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.delete
    redirect_to cocktail_path(params[:cocktail_id])
  end

  private

  def params_dose
    params.require(:dose).permit(:description, :ingredient_id)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
    @doses = Dose.where(cocktail_id: @cocktail.id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  # require_relative "cocktails_controller"

  before_action :set_cocktail, only: [:create, :edit, :update]

  def create
    @review = Review.new(params_review)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review.cocktail = @cocktail
    if @review.save
      redirect_to cocktail_path(@cocktail)
    else
      @score = @cocktail.avg_score
      @reviews = @cocktail.reviews
      @doses = @cocktail.doses
      @dose = Dose.new
      render "cocktails/show"
    end
  end

  def edit; end

  def update; end

  def destroy
    @review = Review.find(params[:id])
    @review.delete
    redirect_to cocktail_path(params[:cocktail_id])
  end

  private

  def params_review
    params.require(:review).permit(:rating, :description)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
    @reviews = Review.where(cocktail_id: @cocktail.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(cocktail) do |f| %>
  <%= f.input :photo, as: :file %>
  <%= f.input :name %>
  <%= f.input :instructions %>
  <%= f.button :submit, "Save", class: "btn btn-outline-light" %>
<% end %>

app/views/cocktails/edit.html.erb
<div class="container">
  <h1>Edit Cocktail</h1>
  <div class="card" style="background-image: url('<%= cl_image_path @cocktail.photo.key, height: 300, width: 400, crop: :fill %>'); margin: 25px 0px 25px;">
  </div>
  <p><%= @cocktail.photo.filename %></p>
  <%= render "form", cocktail: @cocktail %>
  <hr>
  <%= link_to "Back", cocktail_path(@cocktail), :class => "btn btn-outline-light"  %>
</div>

app/views/cocktails/index.html.erb
<div id="index-banner" style="background-image: linear-gradient(rgba(0,0,0,.7),rgba(0,0,0,.7)), url(<%= image_path('rinck-content-studio-6YkD2qD86lg-unsplash.jpg') %>)">
  <h1>Cocktail Space99</h1>
</div>

<div class="container">
  <div class="card-list">
    <% @cocktails.each do |c| %>
      <%= link_to cocktail_path(c) do %>
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path c.photo.key, height: 300, width: 400, crop: :fill %>')">
        <p id="stars"> <% c.avg_score.times do  %><i class="far fa-star" id="irating"></i> <% end %> </p>
        <p class="card-text"><%= c.name %></p>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <h1>New Cocktail</h1>
  <%= render "form", cocktail: @cocktail %>
  <hr>
  <%= link_to "Back", cocktails_path, :class => "btn btn-outline-light" %>
</div>

app/views/cocktails/show.html.erb
<div class="show-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @cocktail.photo.key %>');">
  <h1><%= @cocktail.name %>  </h1>
</div>

<div class="container">
  <div class="ingredient-container">
    <div id="ingredient-list">
      <p id="stars_intro"> <% @cocktail.avg_score.times do  %><i class="far fa-star" id="irating"></i> <% end %> </p>
      <h4>Ingredients</h4>
      <% @doses.each do |dose| %>
        <ul>
          <li><%= dose.description %> of <%= dose.ingredient.name %> <%= link_to "(delete)", cocktail_dose_path(@cocktail, dose), method: :delete, :class => "text-secondary" %></li>
        </ul>
      <% end  %>

      <p></p>
      <div id="instructions">
        <h4>Instructions <%= link_to "(edit)", edit_cocktail_path(@cocktail), :class => "text-secondary" %></h4>
        <p><%= @cocktail.instructions %></p>
      </div>
    </div>

    <div id="ingredient-add">
      <div class="card overlap" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @cocktail.photo.key, height: 300, width: 400, crop: :fill %>')"></div>
      <div class="ingredient-add-form">
        <!-- <h4>Add Ingredient</h4> -->
        <%= render "doses/form", cocktail: @cocktail, dose: @dose %>
      </div>
    </div>
  </div>

  <hr>

  <div class="review-container">
    <div id="review-list">
      <h4>Reviews</h4>
        <% @reviews.each do |review| %>
        <ul>
          <li><p id="stars"> <% review.rating.times do  %><i class="far fa-star" id="irating_small"></i> <% end %> </p></li>
          <li id="review-desc">"<%= review.description %>"</li>
          <p></p>
        </ul>
        <% end %>
    </div>

    <div id="review-add">
      <h5>Add Review</h5>
        <%= render "reviews/form", cocktail: @cocktail, review: @review %>
    </div>
  </div>

  <hr>
  <%= link_to "Back", cocktails_path, :class => "btn btn-outline-light"  %>
</div>

app/views/doses/_form.html.erb
<%= simple_form_for [cocktail, dose] do |f| %>
  <%= f.input :description, label: "Add Fuel Quantity " %>
  <%= f.association :ingredient, label: "Add Fuel"  %>
  <%= f.button :submit, "Add", class: "btn btn-outline-light" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Space99</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <nav class="fixed-top navbar-dark navbar-lewagon">
      <%= link_to cocktails_path do %><span class="navbar-brand mb-0 h1">Cocktail Space99</span><% end %>
      <div>
        <%= link_to "Home", cocktails_path,:class => "btn btn-outline-light" %>
        <%= link_to "New cocktail", new_cocktail_path, :class => "btn btn-outline-light" %>
      </div>
   </nav>
      <%= yield %>
  <div class="footer">
  <div class="footer-copyright">
    <i class="fas fa-copyright"></i> 2999 Actually I Prefer Hot Chocolate Productions
  </div>
  <div class="footer-copyright">
    Vacancies: Only astronauts or home-alone coders need apply <i class="fab fa-github"></i>
  </div>
</div>
  </body>
</html>

app/views/pages/_shared.html.erb
_shared.html.erb

app/views/reviews/_form.html.erb
<%= simple_form_for [cocktail, review], :url => cocktail_reviews_path(cocktail), :method => :post do |f| %>
  <%= f.input :rating %>
  <%= f.input :description %>
  <%= f.button :submit, "Add", class: "btn btn-outline-light"%>
<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>